[package]
name = "ut99-strings"
description = "Tool to extract ASCII strings from UT99 DEMOs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.11"
parameterized = "1.0.1"
predicates = "3.0.3"
